### ISSUE TITLE
StackOverflowException when using `RESET` in interactive mode

### ISSUE THREAD

**Issue by Unknown6656** [Unknown6656/AutoIt-Interpreter#190]
### Steps to reproduce
1. Start with `autoit3 --mode interactive`
2. Type `RESET`
3. Press <kbd>Enter</kbd>
4. A `StackOverflowException` occurs.

### Expected behaviour
The interactive session gets reset

### Stack Trace
```
   ...
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.Runtime.VariableScope.DestroyAllVariables(Boolean)
   at Unknown6656.AutoIt3.CLI.InteractiveShell.Reset()
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c.<ProcessStatement>b__77_27(Unknown6656.AutoIt3.CLI.InteractiveShell)
   at Unknown6656.Generics.LINQ.Do[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c__DisplayClass77_0.<ProcessStatement>b__2(System.Text.RegularExpressions.Match)
   at Unknown6656.Common.StringExtensions.Match[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, System.__Canon, System.ValueTuple`2<System.Text.RegularExpressions.Regex,System.Func`2<System.Text.RegularExpressions.Match,System.__Canon>>[])
   at Unknown6656.Common.StringExtensions.Match[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, System.__Canon, System.Collections.Generic.Dictionary`2<System.Text.RegularExpressions.Regex,System.Func`2<System.Text.RegularExpressions.Match,System.__Canon>>)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c__DisplayClass77_0.<ProcessStatement>b__0()
   at Unknown6656.AutoIt3.Telemetry.Measure[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Unknown6656.AutoIt3.TelemetryCategory, System.Func`1<System.__Canon>)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame.ProcessStatement(System.String)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c__DisplayClass74_0.<ParseCurrentLine>g__TryDo|1(System.Func`2<System.String,Unknown6656.AutoIt3.Runtime.FunctionReturnValue>)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c__DisplayClass74_0.<ParseCurrentLine>b__0()
   at Unknown6656.AutoIt3.Telemetry.Measure(Unknown6656.AutoIt3.TelemetryCategory, System.Action)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame.ParseCurrentLine()
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame+<>c__DisplayClass64_0.<InternalExec>b__0()
   at Unknown6656.AutoIt3.Telemetry.Measure[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Unknown6656.AutoIt3.TelemetryCategory, System.Func`1<System.__Canon>)
   at Unknown6656.AutoIt3.Runtime.AU3CallFrame.InternalExec(Unknown6656.AutoIt3.Runtime.Variant[])
   at Unknown6656.AutoIt3.Runtime.CallFrame+<>c__DisplayClass26_0.<Execute>b__2()
   at Unknown6656.AutoIt3.Telemetry.Measure[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Unknown6656.AutoIt3.TelemetryCategory, System.Func`1<System.__Canon>)
   at Unknown6656.AutoIt3.Runtime.CallFrame.Execute(Unknown6656.AutoIt3.Runtime.Variant[])
   at Unknown6656.AutoIt3.Runtime.AU3Thread.Call(Unknown6656.AutoIt3.Runtime.ScriptFunction, Unknown6656.AutoIt3.Runtime.Variant[], Unknown6656.AutoIt3.Runtime.InterpreterRunContext)
   at Unknown6656.AutoIt3.Runtime.AU3Thread+<>c__DisplayClass29_0.<Run>b__0()
   at Unknown6656.AutoIt3.Telemetry.Measure[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Unknown6656.AutoIt3.TelemetryCategory, System.Func`1<System.__Canon>)
   at Unknown6656.AutoIt3.Runtime.AU3Thread.Run(Unknown6656.AutoIt3.Runtime.ScriptFunction, Unknown6656.AutoIt3.Runtime.Variant[], Unknown6656.AutoIt3.Runtime.InterpreterRunContext)
   at Unknown6656.AutoIt3.Runtime.Interpreter.Run(Unknown6656.AutoIt3.Runtime.ScriptFunction, Unknown6656.AutoIt3.Runtime.Variant[], Unknown6656.AutoIt3.Runtime.InterpreterRunContext)
   at Unknown6656.AutoIt3.Runtime.Interpreter.Run(Unknown6656.AutoIt3.Runtime.ScannedScript, Unknown6656.AutoIt3.Runtime.InterpreterRunContext)
   at Unknown6656.AutoIt3.CLI.InteractiveShell.ProcessInput()
   at Unknown6656.AutoIt3.CLI.InteractiveShell.HandleKeyPress()
   at Unknown6656.AutoIt3.CLI.InteractiveShell.MainLoop()
   at Unknown6656.AutoIt3.CLI.InteractiveShell.Run()
   at Unknown6656.AutoIt3.CLI.MainProgram+<>c__DisplayClass42_1.<Start>b__4(Unknown6656.AutoIt3.CLI.CommandLineOptions)
   at CommandLine.ParserResultExtensions.WithParsed[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](CommandLine.ParserResult`1<System.__Canon>, System.Action`1<System.__Canon>)
   at Unknown6656.AutoIt3.CLI.MainProgram+<>c__DisplayClass42_0.<Start>b__1()
   at Unknown6656.AutoIt3.Telemetry+<>c__DisplayClass19_0.<Measure>b__0()
   at Unknown6656.AutoIt3.Telemetry.Measure[[__empty, Unknown6656.Core, Version=1.1.10.0, Culture=neutral, PublicKeyToken=null]](Unknown6656.AutoIt3.TelemetryCategory, System.Func`1<__empty>)
   at Unknown6656.AutoIt3.Telemetry.Measure(Unknown6656.AutoIt3.TelemetryCategory, System.Action)
   at Unknown6656.AutoIt3.CLI.MainProgram.Start(System.String[])
   at Program.<Main>$(System.String[])
```

### Used system
 - OS: Microsoft Windows [Version 10.0.22631.3296]
 - Interpreter Version: _v.0.10.2189.8634_
 - Commit hash: 1ee855f70f3a4f52564452a2313a3d1f2fd16eb8

**Comment by Unknown6656** [comment]
299b695eb83723253d782ab3840bac5198326317
c94261c5816f150e0db43bd84555b6af69cd3a15
